language: rust
cache: cargo
rust:
    - 1.26.0
    - stable
    - beta
    - nightly
os:
    - windows
    - linux
    - osx

before_script:
    - |
      (travis_wait rustup component add rustfmt-preview || true) &&
      (test "$TRAVIS_RUST_VERSION" == 1.26.0 || travis_wait rustup component add clippy )

script:
    - |
      export PATH="$PATH":~/.cargo/bin &&
      export RUST_BACKTRACE=1 &&
      export CARGO_INCREMENTAL=1 &&
      (test "$TRAVIS_RUST_VERSION" == 1.26.0 || rm -f Cargo.lock) &&
      # for all targets on all platforms
      cargo build --package signal-hook --package signal-hook-registry &&
      cargo doc --no-deps &&
      # for stable/beta/nightly on all platforms
      (test "$TRAVIS_RUST_VERSION" == 1.26.0 || cargo test   --package signal-hook --package signal-hook-registry) &&
      (test "$TRAVIS_RUST_VERSION" == 1.26.0 || cargo clippy --package signal-hook --package signal-hook-registry --tests -- --deny clippy::all) &&
      (test "$TRAVIS_RUST_VERSION" == 1.26.0 || cargo fmt) &&
      # for beta/nightly on macOS/linux
      (test "$TRAVIS_RUST_VERSION" == 1.26.0 || test "$TRAVIS_RUST_VERSION" == "stable" || test "$TRAVIS_OS_NAME" == "windows" || cargo build  --all --all-features) &&
      (test "$TRAVIS_RUST_VERSION" == 1.26.0 || test "$TRAVIS_RUST_VERSION" == "stable" || test "$TRAVIS_OS_NAME" == "windows" || cargo test   --all --all-features) &&
      (test "$TRAVIS_RUST_VERSION" == 1.26.0 || test "$TRAVIS_RUST_VERSION" == "stable" || test "$TRAVIS_OS_NAME" == "windows" || cargo clippy --package tokio-tests --tests -- --deny clippy::all)

matrix:
    allow_failures:
        - rust: nightly
